[tools]
node = "24.15.0"
"npm:pnpm" = { version = "11.0.3", depends = "node" }

[env]
_.file = ".env"

[tasks."dev:template"]
run = "pnpm dev"

[tasks."dev:haqumei-api"]
dir = "../haqumei-api"
run = "mise exec -- cargo run -p haqumei-api"

[tasks.dev]
depends = ["dev:template", "dev:haqumei-api"]
