export {
  avatarOptions,
  avatarSettingsSchema,
  bgmTrackSchema,
  endcardAdvertiserSchema,
  endcardCreditSchema,
  endcardMessageSchema,
  endcardPageMetaSchema,
  ogpMetadataKeys,
  ogpMetadataSchema,
  outroBlockSchema,
  outroPageMetaSchema,
  pageTagsMetaSchema,
  pageTypeSchema,
  projectMetaSchema,
  projectNiconicoMetaSchema,
  transitionVariantSchema,
  voiceOptionSchema,
  voicepeakSynthesisSettingsSchema,
  voicePresetSchema,
  voiceProviderSchema,
  voicevoxSynthesisSettingsSchema,
  voisonaSynthesisSettingsSchema,
  weatherForecastSchema,
  weatherForecastsSchema,
  type AvatarSettings,
  type AvatarType,
  type BgmTrack,
  type EndcardAdvertiser,
  type EndcardCredit,
  type EndcardMessage,
  type OgpMetadata,
  type OutroBlock,
  type PageType,
  type TransitionVariant,
  type VoiceOption,
  type VoicepeakSynthesisSettings,
  type VoicePreset,
  type VoicevoxSynthesisSettings,
  type VoisonaSynthesisSettings,
  type WeatherCondition,
  type WeatherForecast,
  type WeatherForecasts,
  type WeatherLocation,
} from "@/_schemas/project/primitives";

export { savedTtsSchema, type SavedTts } from "@/_schemas/project/tts";

export {
  savedPageSchema,
  savedSequenceItemSchema,
  savedTransitionSchema,
  type SavedEndcardPage,
  type SavedEyecatchTextPage,
  type SavedOutroPage,
  type SavedPage,
  type SavedSequenceItem,
  type SavedTransition,
} from "@/_schemas/project/page";

export {
  copyProjectRequestSchema,
  createProjectRequestSchema,
  projectFileSummarySchema,
  savedProjectSchema,
  type CopyProjectRequest,
  type CreateProjectRequest,
  type ProjectFileSummary,
  type SavedProject,
  type SavedProjectSettings,
} from "@/_schemas/project/project";
