export {
  DEFAULT_KASANE_TETO_EMOTION,
  DEFAULT_PROJECT_META,
  DEFAULT_VOICE_PRESETS,
  DEFAULT_VOICEPEAK_PITCH,
  DEFAULT_VOICEPEAK_SPEED,
  KASANE_TETO_NARRATOR,
  WEATHER_LOCATION_IDS,
  WEATHER_LOCATION_LABELS,
  avatarOptions,
  voicePresetId,
  copyVoiceIdentity,
  getVoiceId,
  getVoiceMatchKey,
  hasVoiceIdentity,
  parseVoiceId,
  toVoiceIdentity,
  ttsVoiceId,
  voiceIdentitiesEqual,
  avatarSettingsSchema,
  bgmTrackSchema,
  endcardAdvertiserSchema,
  endcardCreditSchema,
  endcardMessageSchema,
  endcardPageMetaSchema,
  ogpMetadataKeys,
  ogpMetadataSchema,
  outroBlockSchema,
  outroPageMetaSchema,
  pageTagsMetaSchema,
  pageTypeSchema,
  projectMetaSchema,
  projectNiconicoMetaSchema,
  transitionVariantSchema,
  voiceOptionSchema,
  voicepeakSynthesisSettingsSchema,
  voicePresetSchema,
  voiceProviderSchema,
  voicevoxSynthesisSettingsSchema,
  voisonaSynthesisSettingsSchema,
  coeiroinkSynthesisSettingsSchema,
  weatherConditionSchema,
  weatherForecastSchema,
  weatherForecastsSchema,
  type AvatarSettings,
  type AvatarType,
  type BgmTrack,
  type EndcardAdvertiser,
  type EndcardCredit,
  type EndcardMessage,
  type OgpMetadata,
  type OutroBlock,
  type PageType,
  type TransitionVariant,
  type VoiceOption,
  type VoicepeakSynthesisSettings,
  type VoicePreset,
  type VoicevoxSynthesisSettings,
  type VoisonaSynthesisSettings,
  type CoeiroinkSynthesisSettings,
  type CoeiroinkVoiceIdentity,
  type NamedVoiceIdentity,
  type NamedVoiceProvider,
  type VoiceIdentity,
  type WeatherCondition,
  type WeatherForecast,
  type WeatherForecasts,
  type WeatherLocation,
} from "@/_schemas/project/primitives";

export {
  savedTtsAudioSchema,
  savedTtsSchema,
  type SavedTts,
  type SavedTtsAudio,
} from "@/_schemas/project/tts";

export {
  commentGroupSchema,
  commentSceneSchema,
  commentsNiconicoRefSchema,
  commentsPageMetaSchema,
  commentsPresentationSchema,
  niconicoCommentSchema,
  refineCommentsPageRelations,
  type CommentGroup,
  type CommentScene,
  type CommentsNiconicoRef,
  type CommentsPageMeta,
  type CommentsPresentation,
  type CommentsPageRelationInput,
  type NiconicoComment,
} from "@/_schemas/project/comments";

export {
  savedPageSchema,
  savedSequenceItemSchema,
  savedTransitionSchema,
  type SavedCommentsPage,
  type SavedEndcardPage,
  type SavedEyecatchTextPage,
  type SavedOutroPage,
  type SavedPage,
  type SavedSequenceItem,
  type SavedTransition,
} from "@/_schemas/project/page";

export {
  savedProjectSchema,
  type SavedProject,
  type SavedProjectSettings,
} from "@/_schemas/project/project";
