export const OUTRO_PAGE_DURATION_SEC = 5;
export const OUTRO_BLOCKS_PER_PAGE = 2;
export const OUTRO_CARDS_DELAY_SEC = 0.5;
export const OUTRO_PAPER_HOLD_AFTER_PAGE_SEC = -0.3;
export const OUTRO_PAPER_FADE_OUT_SEC = 0.25;
export const OUTRO_PAPER_MOUNT_DURATION_SEC =
  OUTRO_PAGE_DURATION_SEC + OUTRO_PAPER_HOLD_AFTER_PAGE_SEC + OUTRO_PAPER_FADE_OUT_SEC;
