import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { glob } from "tinyglobby";

const rootDir = process.cwd();
const outputFile = resolve(rootDir, "src/_shared/lib/assets/types.ts");
const ignoredAssetPatterns = ["public/tts/**", "public/uploads/**", "**/.*"];

const formatArray = (values: string[]) => {
  if (values.length === 0) {
    return "[] as const";
  }

  return `[${values.map((value) => JSON.stringify(value)).join(", ")}] as const`;
};

const buildSource = (files: string[]) => {
  const assetFiles = files.map((file) => file.replace(/^public\//u, ""));
  const assetPaths = assetFiles.map((file) => `/${file}`);

  return `// This file is auto-generated by scripts/assets/generate.ts.
// Do not edit manually.

export const assetFiles = ${formatArray(assetFiles)};

export type AssetFile = (typeof assetFiles)[number];

export const assetPaths = ${formatArray(assetPaths)};

export type AssetPath = (typeof assetPaths)[number];
`;
};

export const generateAssets = async () => {
  const files = await glob("public/**/*", {
    cwd: rootDir,
    ignore: ignoredAssetPatterns,
    onlyFiles: true,
  });
  const sortedFiles = [...files].sort((left, right) => left.localeCompare(right));
  const source = buildSource(sortedFiles);
  const currentSource = (() => {
    try {
      return readFileSync(outputFile, "utf8");
    } catch {
      return null;
    }
  })();

  if (currentSource === source) {
    return false;
  }

  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, source);

  return true;
};

await generateAssets();
